import type { BannerSettings, PlayerData } from "./types";

export const defaultSettings: BannerSettings = {
  riotId: "SpyArt#6791",
  platform: "eun1",
  style: "crest",
  accent: "#c89b3c",
  showIcon: true,
  showRecord: true,
  showWinrate: true,
  queue: "solo",
  background: "#111318",
  textColor: "#f5f5f7",
  opacity: 96,
  radius: 12,
  scale: 100,
  font: "sans",
  showTag: true,
  showRegion: true,
  showLevel: true,
  showRank: true,
  showLP: true,
  showGames: false,
  showProgress: true,
  glow: true,
  animate: false,
  showStreak: true,
  showForm: true,
  showKda: true,
  showCs: false,
  showTop: true,
  extraView: "strip",
  theme: "classic",
  speed: 100,
  topCount: 3,
  showMastery: false,
  showTopline: true,
  avatarShape: "round",
  lang: "pl",
};

export const samplePlayer: PlayerData = {
  riotId: "SpyArt#6791",
  gameName: "SpyArt",
  tagLine: "6791",
  platform: "eun1",
  summonerLevel: 246,
  profileIconUrl:
    "https://ddragon.leagueoflegends.com/cdn/15.1.1/img/profileicon/29.png",
  solo: {
    queueType: "RANKED_SOLO_5x5",
    tier: "GOLD",
    rank: "III",
    leaguePoints: 50,
    wins: 19,
    losses: 19,
    hotStreak: true,
  },
  flex: null,
  mastery: {
    score: 412,
    top: [
      { championId: 1, name: "Annie", level: 7, points: 182000, iconUrl: "" },
      { championId: 2, name: "Olaf", level: 6, points: 96000, iconUrl: "" },
      { championId: 3, name: "Galio", level: 5, points: 54000, iconUrl: "" },
    ],
  },
  recent: {
    games: [true, true, false, true, false, true, true, false, true, true],
    kda: 3.4,
    csPerMin: 6.8,
  },
  updatedAt: new Date().toISOString(),
};

export const platforms = [
  ["euw1", "EU West"],
  ["eun1", "EU Nordic & East"],
  ["na1", "North America"],
  ["kr", "Korea"],
  ["br1", "Brazil"],
  ["jp1", "Japan"],
  ["tr1", "Türkiye"],
  ["la1", "LAN"],
  ["la2", "LAS"],
  ["oc1", "Oceania"],
  ["ru", "Russia"],
  ["ph2", "Philippines"],
  ["sg2", "Singapore"],
  ["th2", "Thailand"],
  ["tw2", "Taiwan"],
  ["vn2", "Vietnam"],
] as const;
